Update TIPS_FOR_BASH

diff --git a/TIPS_FOR_BASH b/TIPS_FOR_BASH
--- a/TIPS_FOR_BASH
+++ b/TIPS_FOR_BASH
@@ -4,9 +4,18 @@
 # --------------------------------------------------------------------
 # https://arslan.io/2019/07/03/how-to-write-idempotent-bash-scripts/
 # https://timvisee.com/blog/elegant-bash-conditionals/
+# https://eklitzke.org/bash-$*-and-$@
+
+
+# script parameters
+$*	 # $1 $2 $3...
+$@	 # $1 $2 $3...
+"$*" # "$1 $2 $3..."
+"$@" # "$1" "$2" "$3"...
+
+
 
 # simple if-statements
-
 if [ expression ]
 then
     command
@@ -33,12 +42,10 @@ fi
 # We can simplify this using control operators
 
 [ -r ~/.profile ] && . ~/.profile
-
 cat ~/.profile && echo This is your profile || echo Failed to read profile
 init && configure && install && cleanup || echo Install failed
 
 # A function or script returns the exit code of the last expression
-
 test -f "FILE" && source "$_" || echo "$_ does not exist" >&2
 
 # job control
@@ -56,6 +63,21 @@ test -f "FILE" && source "$_" || echo "$_ does not exist" >&2
 # -o pipefail - Exit if a command in a piped series of commands fails.
 
 set -euo pipefail
+
+# Optional arguments
+# Adding :- after the variable name tells Bash that the string following :- should be used as the value when the variable has not been set.
+
+set -o nounset
+docker_file="${1:-Dockerfile-build}"
+
+# Sensitive data
+# If your script is going to work with sensitive data, passwords or secret tokens
+
+set +o xtrace
+set -o xtrace
+
+# Exit on error
+set -o errexit
 
 # Never use mkdir directly, instead use it with the-p flag. This flag make sure mkdir won’t error if the directory exists
 
